# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20170221_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
