# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_registro_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='producto_registrado',
        ),
        migrations.AddField(
            model_name='registro',
            name='productos',
            field=models.ManyToManyField(blank=True, to='Products.Producto'),
        ),
    ]
