# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20170221_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
